name: Trakt Sync

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run Trakt Sync
      env:
        SIMKL_CLIENT_ID: ${{ secrets.SIMKL_CLIENT_ID }}
        TRAKT_CLIENT_ID: ${{ secrets.TRAKT_CLIENT_ID }}
        TRAKT_CLIENT_SECRET: ${{ secrets.TRAKT_CLIENT_SECRET }}
        SIMKL_ACCESS_TOKEN: ${{ secrets.SIMKL_ACCESS_TOKEN }}
        TRAKT_TOKENS: ${{ secrets.TRAKT_TOKENS }}
      run: node sync-github.js
